import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { UserService } from '../services/user.service';
import { NativeStorage } from '@ionic-native/native-storage/ngx';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements OnInit {
  username = "";
  mobile = "";
  otp = ""; //otp filled by user in register page 
  generatedOtp = ""; //otp generated by UserServices
  otpErrorMessage = ""; //error message when otp mismatch
  usernameErrorMessage = ""; //error message when username empty
  mobileErrorMessage = ""; //error message when phone empty

  constructor(private route: Router, private userService: UserService, private nativeStorage: NativeStorage) {

    //this will check the user already logged in or not if yes then route to dashboard else to register page 
    this.getUsername();
  }

  ngOnInit() {
  }

  //get username that is already stored in native storage
  getUsername() {
    this.nativeStorage.getItem('username')
      .then(
        data =>{ 
          if(data != ""){
            this.route.navigate(['dashboard']);
          }
        }
      );
  }

  //validate Username
  validateUsername() {
    this.usernameErrorMessage = "";
    this.mobileErrorMessage = "";
    if (this.username == "") {
      this.usernameErrorMessage = "Username can not be Empty."
    }
  }

  //validate mobile number and generate otp 
  validatMobile() {
    this.validateUsername();
    var phoneno = /^\d{10}$/;
    if (this.mobile == "") {
      this.mobileErrorMessage = "Please Fill the Mobile Number."
    }
    else {
      if (this.mobile.match(phoneno)) {
        if (this.otp == "")
          this.generatedOtp = this.userService.generateOtp();
      }
      else {
        this.generatedOtp = "Please check Number"
      }
    }
  }

  //otp validation
  validateOtp() {
    this.otpErrorMessage = "";
    this.validatMobile();
    if (this.otp.length == 4) {
      if (this.otp != this.generatedOtp) {
        this.otpErrorMessage = "OTP Mismatch !!"
      }
      else {
        //set username in native storage
        this.nativeStorage.setItem('username', this.username);

        //user mobile number
        this.nativeStorage.setItem('mobile', this.mobile);

        this.route.navigate(['dashboard']);
      }
    }
  }


}
